### ISSUE TITLE
Tags cloud doesnt work

### ISSUE THREAD

**Issue by outluch** [gothinkster/vue-realworld-example-app#274] opened 2019-11-13 20:22 UTC
I click on tag but nothing happens. https://vue-vuex-realworld.netlify.com/#/
In original version it works: https://demo.realworld.io/#/

**Comment by igeligel** [comment] 2019-11-18 08:54
Hey @outluch ,

I cannot reproduce this:

![](https://i.imgur.com/8yayajM.gif)

It is working as expected. Closing this issue in 24 hours if there are no other concerns.

**Closed** 2019-11-19 08:17 UTC

**Comment by mindochin** [comment] 2019-12-05 07:03
confirm, not work
![record_000001](https://user-images.githubusercontent.com/1146472/70211565-41b20200-1757-11ea-8521-32acd98bfcfd.gif)
